/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AppTransactionsRouteImport } from './routes/_app.transactions'
import { Route as AppSuspenseRouteImport } from './routes/_app.suspense'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCollectionsRouteImport } from './routes/_app.collections'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppDevelopersWebhooksRouteImport } from './routes/_app.developers.webhooks'
import { Route as AppDevelopersAuditRouteImport } from './routes/_app.developers.audit'
import { Route as AppDevelopersApiKeysRouteImport } from './routes/_app.developers.api-keys'
import { Route as AppAdminSweepsRouteImport } from './routes/_app.admin.sweeps'
import { Route as AppAdminSuspenseRouteImport } from './routes/_app.admin.suspense'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppAdminSecurityRouteImport } from './routes/_app.admin.security'
import { Route as AppAdminReconRouteImport } from './routes/_app.admin.recon'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin.audit'
import { Route as AppAdminTenantsIndexRouteImport } from './routes/_app.admin.tenants.index'
import { Route as AppAdminTenantsTenantIdRouteImport } from './routes/_app.admin.tenants.$tenantId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSuspenseRoute = AppSuspenseRouteImport.update({
  id: '/suspense',
  path: '/suspense',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersWebhooksRoute = AppDevelopersWebhooksRouteImport.update({
  id: '/developers/webhooks',
  path: '/developers/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersAuditRoute = AppDevelopersAuditRouteImport.update({
  id: '/developers/audit',
  path: '/developers/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersApiKeysRoute = AppDevelopersApiKeysRouteImport.update({
  id: '/developers/api-keys',
  path: '/developers/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSweepsRoute = AppAdminSweepsRouteImport.update({
  id: '/admin/sweeps',
  path: '/admin/sweeps',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSuspenseRoute = AppAdminSuspenseRouteImport.update({
  id: '/admin/suspense',
  path: '/admin/suspense',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSecurityRoute = AppAdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReconRoute = AppAdminReconRouteImport.update({
  id: '/admin/recon',
  path: '/admin/recon',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTenantsIndexRoute = AppAdminTenantsIndexRouteImport.update({
  id: '/admin/tenants/',
  path: '/admin/tenants/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTenantsTenantIdRoute = AppAdminTenantsTenantIdRouteImport.update({
  id: '/admin/tenants/$tenantId',
  path: '/admin/tenants/$tenantId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accounts': typeof AppAccountsRoute
  '/collections': typeof AppCollectionsRoute
  '/customers': typeof AppCustomersRoute
  '/settings': typeof AppSettingsRoute
  '/suspense': typeof AppSuspenseRoute
  '/transactions': typeof AppTransactionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/recon': typeof AppAdminReconRoute
  '/admin/security': typeof AppAdminSecurityRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/suspense': typeof AppAdminSuspenseRoute
  '/admin/sweeps': typeof AppAdminSweepsRoute
  '/developers/api-keys': typeof AppDevelopersApiKeysRoute
  '/developers/audit': typeof AppDevelopersAuditRoute
  '/developers/webhooks': typeof AppDevelopersWebhooksRoute
  '/admin/': typeof AppAdminIndexRoute
  '/admin/tenants/$tenantId': typeof AppAdminTenantsTenantIdRoute
  '/admin/tenants/': typeof AppAdminTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accounts': typeof AppAccountsRoute
  '/collections': typeof AppCollectionsRoute
  '/customers': typeof AppCustomersRoute
  '/settings': typeof AppSettingsRoute
  '/suspense': typeof AppSuspenseRoute
  '/transactions': typeof AppTransactionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/': typeof AppIndexRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/recon': typeof AppAdminReconRoute
  '/admin/security': typeof AppAdminSecurityRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/suspense': typeof AppAdminSuspenseRoute
  '/admin/sweeps': typeof AppAdminSweepsRoute
  '/developers/api-keys': typeof AppDevelopersApiKeysRoute
  '/developers/audit': typeof AppDevelopersAuditRoute
  '/developers/webhooks': typeof AppDevelopersWebhooksRoute
  '/admin': typeof AppAdminIndexRoute
  '/admin/tenants/$tenantId': typeof AppAdminTenantsTenantIdRoute
  '/admin/tenants': typeof AppAdminTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/collections': typeof AppCollectionsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/suspense': typeof AppSuspenseRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/recon': typeof AppAdminReconRoute
  '/_app/admin/security': typeof AppAdminSecurityRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/suspense': typeof AppAdminSuspenseRoute
  '/_app/admin/sweeps': typeof AppAdminSweepsRoute
  '/_app/developers/api-keys': typeof AppDevelopersApiKeysRoute
  '/_app/developers/audit': typeof AppDevelopersAuditRoute
  '/_app/developers/webhooks': typeof AppDevelopersWebhooksRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/admin/tenants/$tenantId': typeof AppAdminTenantsTenantIdRoute
  '/_app/admin/tenants/': typeof AppAdminTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/accounts'
    | '/collections'
    | '/customers'
    | '/settings'
    | '/suspense'
    | '/transactions'
    | '/admin/login'
    | '/admin/audit'
    | '/admin/recon'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/suspense'
    | '/admin/sweeps'
    | '/developers/api-keys'
    | '/developers/audit'
    | '/developers/webhooks'
    | '/admin/'
    | '/admin/tenants/$tenantId'
    | '/admin/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sitemap.xml'
    | '/accounts'
    | '/collections'
    | '/customers'
    | '/settings'
    | '/suspense'
    | '/transactions'
    | '/admin/login'
    | '/'
    | '/admin/audit'
    | '/admin/recon'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/suspense'
    | '/admin/sweeps'
    | '/developers/api-keys'
    | '/developers/audit'
    | '/developers/webhooks'
    | '/admin'
    | '/admin/tenants/$tenantId'
    | '/admin/tenants'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/sitemap.xml'
    | '/_app/accounts'
    | '/_app/collections'
    | '/_app/customers'
    | '/_app/settings'
    | '/_app/suspense'
    | '/_app/transactions'
    | '/admin/login'
    | '/_app/'
    | '/_app/admin/audit'
    | '/_app/admin/recon'
    | '/_app/admin/security'
    | '/_app/admin/settings'
    | '/_app/admin/suspense'
    | '/_app/admin/sweeps'
    | '/_app/developers/api-keys'
    | '/_app/developers/audit'
    | '/_app/developers/webhooks'
    | '/_app/admin/'
    | '/_app/admin/tenants/$tenantId'
    | '/_app/admin/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suspense': {
      id: '/_app/suspense'
      path: '/suspense'
      fullPath: '/suspense'
      preLoaderRoute: typeof AppSuspenseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections': {
      id: '/_app/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/webhooks': {
      id: '/_app/developers/webhooks'
      path: '/developers/webhooks'
      fullPath: '/developers/webhooks'
      preLoaderRoute: typeof AppDevelopersWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/audit': {
      id: '/_app/developers/audit'
      path: '/developers/audit'
      fullPath: '/developers/audit'
      preLoaderRoute: typeof AppDevelopersAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/api-keys': {
      id: '/_app/developers/api-keys'
      path: '/developers/api-keys'
      fullPath: '/developers/api-keys'
      preLoaderRoute: typeof AppDevelopersApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/sweeps': {
      id: '/_app/admin/sweeps'
      path: '/admin/sweeps'
      fullPath: '/admin/sweeps'
      preLoaderRoute: typeof AppAdminSweepsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/suspense': {
      id: '/_app/admin/suspense'
      path: '/admin/suspense'
      fullPath: '/admin/suspense'
      preLoaderRoute: typeof AppAdminSuspenseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/security': {
      id: '/_app/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AppAdminSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/recon': {
      id: '/_app/admin/recon'
      path: '/admin/recon'
      fullPath: '/admin/recon'
      preLoaderRoute: typeof AppAdminReconRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tenants/': {
      id: '/_app/admin/tenants/'
      path: '/admin/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AppAdminTenantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tenants/$tenantId': {
      id: '/_app/admin/tenants/$tenantId'
      path: '/admin/tenants/$tenantId'
      fullPath: '/admin/tenants/$tenantId'
      preLoaderRoute: typeof AppAdminTenantsTenantIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuspenseRoute: typeof AppSuspenseRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminReconRoute: typeof AppAdminReconRoute
  AppAdminSecurityRoute: typeof AppAdminSecurityRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminSuspenseRoute: typeof AppAdminSuspenseRoute
  AppAdminSweepsRoute: typeof AppAdminSweepsRoute
  AppDevelopersApiKeysRoute: typeof AppDevelopersApiKeysRoute
  AppDevelopersAuditRoute: typeof AppDevelopersAuditRoute
  AppDevelopersWebhooksRoute: typeof AppDevelopersWebhooksRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminTenantsTenantIdRoute: typeof AppAdminTenantsTenantIdRoute
  AppAdminTenantsIndexRoute: typeof AppAdminTenantsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppCollectionsRoute: AppCollectionsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuspenseRoute: AppSuspenseRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminReconRoute: AppAdminReconRoute,
  AppAdminSecurityRoute: AppAdminSecurityRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminSuspenseRoute: AppAdminSuspenseRoute,
  AppAdminSweepsRoute: AppAdminSweepsRoute,
  AppDevelopersApiKeysRoute: AppDevelopersApiKeysRoute,
  AppDevelopersAuditRoute: AppDevelopersAuditRoute,
  AppDevelopersWebhooksRoute: AppDevelopersWebhooksRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminTenantsTenantIdRoute: AppAdminTenantsTenantIdRoute,
  AppAdminTenantsIndexRoute: AppAdminTenantsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
